### ISSUE TITLE
Tinker-V GPIO always occupied by kernal

### ISSUE THREAD

**Issue by YJack0000** [TinkerBoard/TinkerBoard#11]
I am trying to use gpio on tinker-v but the gpio are always occupied by kernal like below. 

![Screenshot 2023-09-23 at 9 13 03 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/c3d25a51-ba93-4540-a965-5249e056556f)

I execute the example files like below

![Screenshot 2023-09-23 at 9 16 56 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/cd812d15-d459-4b44-9bea-26281478a14d)

I saw the example document show that the gpio should be unused when trying to control it by c code. 

![Screenshot 2023-09-23 at 9 15 43 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/807d0dc4-31ec-4e86-b044-77c49f4c56cb)

![Screenshot 2023-09-23 at 9 16 10 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/74bdd9ba-2c64-4855-b0a0-4c41d7a7310a)

What might be the problem? I have check whether there is proccess occupying gpio

![Screenshot 2023-09-23 at 9 25 31 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/b6d8a341-4525-44d0-bd5d-33b7acb0d6b0)

And the kernal_modeuls is only about v4l2

![Screenshot 2023-09-23 at 9 25 58 PM](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/c0571f83-d7e7-4ce5-9315-7864a36f950b)

**Comment by Roooock** [comment]
Due to the SPI0 enabled by default, we need to disable the SPI0.
Please apply this patch on the  source_code/meta-asus-renesas, then re-build and flash image.

[0001-disable-SPI0-for-Tinker-V.patch](https://github.com/TinkerBoard/TinkerBoard/files/12724177/0001-disable-SPI0-for-Tinker-V.patch)

**Comment by YJack0000** [comment]
I saw the patch will generate another patch. Should I patch another patch? Or rebuild the image with the generated patch

**Comment by Roooock** [comment]
Please apply it on the meta-asus-renesas folder directly, it will patch the kernel when building yocto image.

**Comment by YJack0000** [comment]
Is that possible to set gpio to input mode instead of output?

**Comment by Roooock** [comment]
> Is that possible to set gpio to input mode instead of output?

Could you use the gpiod_line_request_input() API to set the direction to input?

**Comment by YJack0000** [comment]
I have patched the config and tried to rebuild the images
But after I apply the patch, the root file system core-image-bsp-rzfive-tinker-v.tar.bz2 build failed

**Comment by YJack0000** [comment]
```
NOTE: > Executing update_gtk_icon_cache intercept ...
NOTE: > Executing update_gtk_immodules_cache intercept ...
NOTE: Exit code 1. Output:
/source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/intercept_scripts-98cbc73ee7147a3f84f590fd124b54098f3eafa71bf72dcc76d8a37cff9aaff7/update_gtk_immodules_cache: 15: cannot create /source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/rootfs/usr/lib/gtk-3.0/3.0.0/immodules.cache: Directory nonexistent
chown: cannot access '/source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/rootfs/usr/lib/gtk-3.0/3.0.0/immodules.cache': No such file or directory

ERROR: The postinstall intercept hook 'update_gtk_immodules_cache' failed, details in /source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/temp/log.do_rootfs
DEBUG: Python function do_rootfs finishedNOTE: > Executing update_gtk_icon_cache intercept ...
NOTE: > Executing update_gtk_immodules_cache intercept ...
NOTE: Exit code 1. Output:
/source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/intercept_scripts-98cbc73ee7147a3f84f590fd124b54098f3eafa71bf72dcc76d8a37cff9aaff7/update_gtk_immodules_cache: 15: cannot create /source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/rootfs/usr/lib/gtk-3.0/3.0.0/immodules.cache: Directory nonexistent
chown: cannot access '/source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/rootfs/usr/lib/gtk-3.0/3.0.0/immodules.cache': No such file or directory

ERROR: The postinstall intercept hook 'update_gtk_immodules_cache' failed, details in /source/build/tmp/work/rzfive_tinker_v-poky-linux/core-image-bsp/1.0-r0/temp/log.do_rootfs
DEBUG: Python function do_rootfs finished
```
