### ISSUE TITLE
tinker board 2s android 11 update kernel

### ISSUE THREAD

**Issue by bbddn** [TinkerBoard/TinkerBoard#14]
In the case of Tinkerboard Debian Linux kernel, only the kernel can be updated using the command below.
sudo dd if=boot.img of=/dev/mmcblk1p4 status=progress && sync

How can only the kernel of Tinkerboard Android 11 kernel be updated?

For Android, is there only way to update the entire system with the WW_Tinker_Board_2-raw.img image?

**Comment by Roooock** [comment]
You can update kernel via fastboot command for Android OS.
```
adb reboot fastboot
fastboot flash boot boot.img
fastboot reboot
```

**Comment by bbddn** [comment]
> You can update kernel via fastboot command for Android OS.
> 
> ```
> adb reboot fastboot
> fastboot flash boot boot.img
> fastboot reboot
> ```

It works!
Good Thank you
