### ISSUE TITLE
Building cmake on tinker-v

### ISSUE THREAD

**Issue by pepe996** [TinkerBoard/TinkerBoard#16]
I've followed [tinker-v's wiki](https://github.com/TinkerBoard/TinkerBoard/wiki/Tinker-V) to build the image and flash it on the board, and there is gcc/g++ available after setting up the environment. Now i have a cmake project, but there is no such command as well as package management command like apt-get or yum to install cmake directly. So i'd like to build cmake command from source via wget, but it seems like there's some issues for g++:
![image](https://github.com/TinkerBoard/TinkerBoard/assets/60679302/4494b9cf-dbbe-4da8-8a2a-5937ddd9b61a)

Checking the error log:
![image](https://github.com/TinkerBoard/TinkerBoard/assets/60679302/9686b37c-4c28-455b-a1e6-4eeb154c8af7)
![image](https://github.com/TinkerBoard/TinkerBoard/assets/60679302/9cc92331-97e9-4750-ab5b-8fe7fedbd6c1)

I've noticed that #5 had the same issue, and it seems like it's a bug from the built image. However, the link provided below seems to be expired, and I do not have permission to access it. Is the [repo for tinker-v environment build](https://github.com/TinkerBoard/renesas-manifest) up-to-date? Or is there any other gcc/g++ that can run on tinker-v without this issue? (Have tried `riscv-gnu-toolchain` and encountered same issue as #6) And i'm also unsure that whether my flow of building cmake on tinker-v is correct or valid.

**Comment by Roooock** [comment]
If you want to install CMake on Tinker V, you can add cmake in the rzfive-tinker-v.conf.
a. Edit  meta-asus-renesas/conf/machine/rzfive-tinker-v.conf
b. Add cmake in the CORE_IMAGE_EXTRA_INSTALL.
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/5caa6498-d783-40e2-b101-c54c5d45f360)
c. Build the image and update rootfs image(core-image-bsp-rzfive-tinker-v.tar.bz2) to eMMC or SD card.
d. Now you can use the CMake.
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/7a953300-83cb-4e64-b4e6-80774ef55096)

**Comment by pepe996** [comment]
Thanks! I will try this later. How about the gcc/g++ issue in #5? Do i need another rootfs image `core-image-bsp-rzfive-tinker-v.tar.bz2`? Seems like you've provided another one but i have no access to that link (or it is expired).

**Comment by Roooock** [comment]
This is a simple example compiled using g++.
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/c27253af-720f-4957-8f4e-554d241b3c92)

**Comment by pepe996** [comment]
Have built cmake successfully on tinker-v, thanks for the help! 
g++ also works fine with the additional include path. For cmake usage, adding the following two lines to `CMakeLists.txt` can add the compiler flag:
```
set(CXXFLAGS "-I/usr/include/c++/8.3.0/riscv64-poky-linux")
set(CMAKE_CXX_FLAGS "${CXXFLAGS}")
```
