### ISSUE TITLE
Where is the rockdev?

### ISSUE THREAD

**Issue by Zaryob** [TinkerBoard/TinkerBoard#3]
In following page [Developer Guide Kernel 4.19 compilation](https://github.com/TinkerBoard/TinkerBoard/wiki/Developer-Guide#kernel-419) it says that

>
> You can issue the following command to build all the images for Debian. All the images will be saved in the directory rockdev.
>
>   $ ./build.sh
>

And it is not obvious that where is the rockdev??

**Comment by asusiot** [comment]
hello @Zaryob, 
"It will generate a file which named sdboot.img and located at [source tree]/rockdev/sdboot.img"

it depends on where your source tree is located

**Comment by Zaryob** [comment]
I was asked to what is rockdev. And I found it. I cloned [https://github.com/TinkerBoard2/device-rockchip](https://github.com/TinkerBoard2/device-rockchip)  repository. And moved files into `~/devices/rockchip` and ./build.sh is on tinker_board_2 directory. And I also renamed `tinker_board_2`  as `.target_product`

**Comment by Zaryob** [comment]
I'm stating them to show how I did it if anyone also needs to generate an image from scratch.
