### ISSUE TITLE
Is there other information about tinker-v?  

### ISSUE THREAD

**Issue by YJack0000** [TinkerBoard/TinkerBoard#5]
Where are the BSP source file? 
I ran
```
sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib \
build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
xz-utils debianutils iputils-ping libsdl1.2-dev xterm p7zip-full sudo \
libyaml-dev libssl-dev
```
And it not contain the `./build.sh` file

**Comment by asusiot** [comment]
hello @YJack0000 

it's necessary to download the source code / set up the docker enviornment; we've uploaded the wiki for your reference: https://github.com/TinkerBoard/TinkerBoard/wiki/Tinker-V

sorry for the inconvenience

**Comment by YJack0000** [comment]
Thanks for your reply. I have built the OS successfully!
However, in the fdisk part in the instruction below
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/a52723f5-fe63-44b6-826c-2499f431f22e)

I do not have the fdisk for the partitioning
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/3d887044-30d9-4ce4-94af-b6810db8263f)

Is there something wrong?

**Comment by YJack0000** [comment]
Thanks! I built it successfully

**Comment by YJack0000** [comment]
However, the system seems to have a lot of issues. The 'bits/' directory is unable to be read and is missing many headers. Additionally, the Docker daemon is unable to run. 
I there missing some support of system library?

**Comment by asusiot** [comment]
hello @YJack0000 
looks like the issue is similar to this: https://community.renesas.com/rz/f/rz-forum/30586/rz-five-docker-issue 

updated: tried to reproduce the issue
```
systemctl enable docker.service

systemctl start docker.service

docker run hello-world
```
and daemon runs sucessfully. 

running g++:
![tinker v gcc](https://github.com/TinkerBoard/TinkerBoard/assets/89904531/7edf4574-526e-4934-a16a-17cfd1baade8)


would you mind providing us steps to reproduce and logs (if theres any) to specify the issue?

**Comment by YJack0000** [comment]
The g++ compiler with the include just show this
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/97f2713b-8312-437e-8dc0-8a2ad5674741)

And the `hello.cpp` is like below
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/d84a3f15-91b0-4d83-b124-e3f681d13c70)

**Comment by YJack0000** [comment]
How ever the docker daemon works fine~

**Comment by YJack0000** [comment]
trying to use g++ in riscv64/ubuntu images
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/3650b5b1-defc-475f-b645-7c130315c3dd)

and also the similar SE when I just compile the .cpp file through the `riscv64-unknow-elf-g++`

**Comment by YJack0000** [comment]
I even tried to build g++ through gcc XD

**Comment by Roooock** [comment]
> trying to use g++ in riscv64/ubuntu images ![image](https://user-images.githubusercontent.com/49984479/264419443-3650b5b1-defc-475f-b645-7c130315c3dd.png)
> 
> and also the similar SE when I just compile the .cpp file through the `riscv64-unknow-elf-g++`

riscv64/ubuntu images is not support to riscv64 architecture.

![ubuntu_riscv64_support](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/ad8e4509-880e-4671-bbe1-96c4bb4d4ae3)

**Comment by Roooock** [comment]
> The g++ compiler with the include just show this ![image](https://user-images.githubusercontent.com/49984479/264414940-97f2713b-8312-437e-8dc0-8a2ad5674741.png)
> 
> And the `hello.cpp` is like below ![image](https://user-images.githubusercontent.com/49984479/264415228-d84a3f15-91b0-4d83-b124-e3f681d13c70.png)

Please try this rootfs image (This link will expire after one week.)
https://asus-my.sharepoint.com/:u:/r/personal/rock_shen_asus_com/Documents/core-image-bsp-rzfive-tinker-v.tar.bz2?csf=1&web=1&e=xWsClc

**Comment by YJack0000** [comment]
Thanks for the reply about docker image~

However, the rootfs link is not working for me
<img width="937" alt="Screenshot 2023-08-31 at 6 55 21 PM" src="https://github.com/TinkerBoard/TinkerBoard/assets/49984479/bee1207b-88ae-4e5d-bebe-e15ba2e7b89d">

**Comment by asusiot** [comment]
hello @YJack0000 
the permission settings for the link's been changed: https://asus-my.sharepoint.com/:u:/r/personal/rock_shen_asus_com/Documents/core-image-bsp-rzfive-tinker-v.tar.bz2?csf=1&web=1&e=xWsClc

**Comment by YJack0000** [comment]
Still unable to go to the site 
<img width="880" alt="Screenshot 2023-08-31 at 9 04 48 PM" src="https://github.com/TinkerBoard/TinkerBoard/assets/49984479/ecc1f099-6d20-4ff5-b0a4-434dab6f61f0">

**Comment by YJack0000** [comment]
Change to the rootfs and get those message when booting 
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/40b8fdd3-c89b-4a8b-9af3-0e3764e90244)
