### ISSUE TITLE
Tinker-V cross compile problem

### ISSUE THREAD

**Issue by YJack0000** [TinkerBoard/TinkerBoard#6]
The [riscv64-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain) are using c++ 12. Therefore, we can't just replace the header file by using the 8.3.0 c++ in tinker-v bsp. 
Is there a way to configure the toolchain to build tinker-v's program? 

Both `riscv64-unknow-elf-g++` and `riscv64-unknow-elf-gcc` are not able to build a runnable binary to tinker-v. 

The program will just have segmentation fault immdiately when execute it.

**Comment by Roooock** [comment]
Build the toolchain for Tinker V

`$ ./docker_builder/docker-builder-run.sh`
`$ source poky/oe-init-build-env`
`$ bitbake core-image-bsp -c populate_sdk`

Exit docker environment
`$ exit`
 
SDK installer will be located in build/tmp/deploy/sdk, go to folder of sdk
`$ cd build/tmp/deploy/sdk`
 
Install toolchain
`$ sudo sh poky-glibc-x86_64-core-image-bsp-riscv64-rzfive-tinker-v-toolchain-3.1.21.sh`

How to build Linux application for RISC-V
`$ source /opt/poky/3.1.17/environment-setup-riscv64-poky-linux`
`$ riscv64-poky-linux-gcc -o XXX XXX.c --sysroot=/opt/poky/3.1.21/sysroots/riscv64-poky-linux`

**Comment by YJack0000** [comment]
It build successfully~
But it is gnu 8.3.0. 
Is it possible to have gnu 11 for this system? 
Because I want to build other things like tvm, opencv, tengine, etc. And mostly required c++ >= 11 for it.

**Comment by Roooock** [comment]
Alternatively, you can compile and install the riscv-toolchain for Tinker V.

`sudo apt-get install -y autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev libncurses-dev device-tree-compiler libssl-dev gdisk swig`

`git clone https://github.com/riscv/riscv-gnu-toolchain`
`cd riscv-gnu-toolchain`
`./configure --prefix=/opt/riscv`
`sudo make linux -j`

**Comment by YJack0000** [comment]
I had mad the multilib toolchain by using
```
./configure --prefix=/opt/riscv --enable-multilib
```
what arg should I give to the `riscv64-unknow-elf-g++`? 
I have tried the `--with-arch=rv64gc` and `--with-arch=rv64imafdc`, but both of them will get `Segamentation Fault` while executing the binary in the tinker-v. 
The only things that won't get error is when I compile the binary through the `gcc` or `g++` or `riscv64-poky-linux-gcc`, is there some missing step should I do if I want to use `riscv-gnu-toolchain`?

**Comment by YJack0000** [comment]
There will be a problem of execution file generate by `riscv-unknow-linux-gnu-g++` about
```
 libc.so.6: version `GLIBC_2.34' not found
```
Should I add other thing about `glibc` to make it work?

**Comment by Roooock** [comment]
Unfortunately, the image only supports gcc 8.3.0 (riscv64-poky-linux-gcc) and cannot support riscv64-unknown-linux-gnu-gcc (gcc 12.2.0).

**Comment by YJack0000** [comment]
So the cross compiler cannot support the compiler toolchain?!

**Comment by YJack0000** [comment]
Than does the board support any other AI framework or runtime such like tvm runtime, onnxruntime, etc.? 
Because most of them have to be compiled with c++ >= 11

**Comment by Roooock** [comment]
> So the cross compiler cannot support the compiler toolchain?!

It’s correct.
