### ISSUE TITLE
Tinker-V cannot find /dev/video* problem

### ISSUE THREAD

**Issue by YJack0000** [TinkerBoard/TinkerBoard#7]
I want to connect my tinker-v to usb camera and read it by using `v4l2`. 

After connected to device, the `/dev/video` are not showing up. 
![372322563_782588663877294_6877619957969966697_n](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/0810592c-77e8-4f77-9c9b-184ac9d698b6)

However, I checked `lsusb` and the device is shown correctly. 
![375441397_266679536308773_7672768942224592330_n](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/36846b7b-2791-4446-9434-a77d3bbca526)

But I have connect it to my other device like raspberry pi and computer with ubuntu system to check camera works. 

Is there something I should do inorder to connect camera to tinker-v?

**Comment by Roooock** [comment]
1. Please add kernel-modules in the meta-asus-renesas/conf/machine/rzfive-tinker-v.conf
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/cd85dfac-b8e3-40cb-930d-effb4db104d2)
2. Rebuild and flash the image
3. `modprobe uvcvideo`

**Comment by YJack0000** [comment]
If I want to add the package management tools like `opkg` or `apt`. How should I add to the image configuration? 
Are they also added in the same place?

**Comment by Roooock** [comment]
You can add opkg to this config, but we do not guarantee that it will work.
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/75f6aa09-86d7-4199-bb60-d9d153a99a9e)
