### ISSUE TITLE
Tinker-v gcc internal error problem when build ffmpeg

### ISSUE THREAD

**Issue by YJack0000** [TinkerBoard/TinkerBoard#8]
I am trying to build the `ffmpeg` in tinker-v, but I encountered a Segmentation fault when building it. 

Here is the step that reproduce the error: 

1. Get the source code from `https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz` and extract the source code. 
2. using `./configure` to generate `Makefile`
3. execute `make`

And here is the error: 
![image](https://github.com/TinkerBoard/TinkerBoard/assets/49984479/4c1d9b54-a5e4-48f6-bed7-0a0b508442e7)

What is the problem? I am trying to use the (cross compiler](https://github.com/TinkerBoard/TinkerBoard/issues/6) to compile the project, but it seems like the results of the cross compiler are also not executable on tinker-v.  

Are there other ways to use ffmpeg?

**Comment by Roooock** [comment]
Could you please try to build the ffmpeg on the SDK?
Add these on the meta-asus-renesas
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/dd191ce9-8359-42b6-9956-29828b8f3ac8)

The ffmpeg can be executed normally on Tinker V.
![image](https://github.com/TinkerBoard/TinkerBoard/assets/5523365/0a89ddad-73ee-4d40-9c03-ee7be1b5c4f5)
