### ISSUE TITLE
Can't create image of Tinker Board 3N

### ISSUE THREAD

**Issue by habehabe** [TinkerBoard/TinkerBoard#9]
The URL below causes a 404 error, so KERNEL SOURCE cannot be obtained.

https://github.com/TinkerBoard3N/kernel

Is the docker_builder directory included in KERNEL SOURCE?
If not, please let me know where to get it.

**Comment by asusiot** [comment]
hello @habehabe 
https://github.com/TinkerBoard/TinkerBoard/wiki/Tinker-Board-3N#1-linux-development

please use the command to download the sources:
`repo init -u https://github.com/TinkerBoard/rockchip-linux-manifest.git -b linux5.10-rk356x`
